### ISSUE TITLE
Web page for IR blasters, or allow .wav files in forum posts

### ISSUE THREAD

**Issue by dave5709** [seamonkeysocial/twitarr#12]
On the last cruise, a number of people were trying to connect consoles and laptops to their room TV HDMI ports.  Changing inputs required having a concierge bring a remote to a room, and the TV would reset the input when turned off & back on.  I'll be making and distributing DIY headphone jack IR blasters to give to people on the ship wanting to use the HDMI inputs on their room TVs.  The range is short, only a few feet, but they'll work well for this purpose.

To prevent having to download & configure an app, I'd like to be able to make a page available on Twit-arr for users.  The page would consist of text, and buttons/links to play tiny .wav files.  If THO provides a list of TV models on the ship, I can provide this in advance, otherwise I'd need to provide this on board.

Alternatively, if tiny .wav files are permitted in forum posts, I could post the .wav files in a forum post once on board.

**Comment by grundoon** [comment]
IMO, best is going to be a static page/files (and best if we have them in advance). They can easily be served up.

Although last year was the first without any real network limitation issues, and ostensibly we'll have have the very same network, I'm not personally comfortable with significantly altering the limitations on  what can be posted as/attached to twarrts/forum posts/seamails. I'm certainly open to being convinced (or outvoted) otherwise, but think that, say, a Forum for the topic with an introductory link to the static content is maybe the best approach.

**Comment by hendusoone** [comment]
Static page and files would definitely be the easiest, and I like the idea of having it linked from a forum thread. That will give users a convenient place to discuss and ask questions about it. I also wonder if it would be worth hooking up to a section in the mobile app - like, have buttons in the app that will download the hosted files, cache them locally for future use, and play them?

**Comment by dave5709** [comment]
I've reached out to THO in the hopes of getting make/model information for all of the room TVs on the ship, but I won't be able to test all of the .wav files from land.  Even if I get a list, there's no guarantee that it will be complete or that I won't make a mistake.  From looking at Oosterdam room videos people have posted online, I've seen Samsung and LG, but most of the time TV brands weren't readable.  If I can at least get a definitive list of brands they use I can create a ton of .wav files at home, but if it's more than a couple of brands with dozens of IR codes it may not be practical.

I can troubleshoot and create new .wav files from the boat on my laptop, but some kind of update mechanism would need to be in place.  A forum post/update seems easier than tracking down the right person on the boat and giving them a flash drive to update the static page.  The .wav files will all be under 200k, and should be cached by the browser after 1st use (not sure about the cruise monkey app).  In theory a browser control inside of the cruise monkey app would allow for the smallest amount of code necessary to replicate the static page.

**Comment by hendricksond** [comment]
Per a recent e-mail, it will not be possible to change the inputs on the TVs this year (or possibly even access the inputs). So, this page won't be implemented.
