### ISSUE TITLE
“Close photo” X icon invisible if photo is dark or does not cover top corner

### ISSUE THREAD

**Issue by chicazul** [seamonkeysocial/twitarr#172]
Web interface. The X icon is transparent, which works if the photo is light coloured and extends to the edge of the photo frame, but since the frane size appears static, if the photo is in a different aspect ratio or happens to be dark in that corner, the black circle around the X blends into the black background and it is impossible to see how to close a photo.

**Comment by hendricksond** [comment]
I re-colored the close icon to use the same blue as the waves in the header. You may need to clear browser cache to see the change. Clicking anywhere except the "open full size" button should close it, anyway.

**Comment by hendricksond** [comment]
In fact, clicking the "open full size" button closes the image, too - but it also opens the image in a new tab/as a download.
