### ISSUE TITLE
Search box in initial server interface is non-functional

### ISSUE THREAD

**Issue by pneumaticdeath** [seamonkeysocial/twitarr#177]
While the search box in the upper right corner of the web interface appears functional, if you select "Search" from the hamburger menu, then the search box on that page is non-responsive. It doesn't seem to initiate a search if I hit return or click on the "Go" button.

**Comment by pneumaticdeath** [comment]
While the search box in the upper right corner of the web interface appears functional, if you select "Search" from the hamburger menu, then the search box on that page is non-responsive.  It doesn't seem to initiate a search if I hit return or click on the "Go" button.

**Comment by hendricksond** [comment]
Bug confirmed, thanks for the report!
