### ISSUE TITLE
"Time zone check" page needs updating

### ISSUE THREAD

**Issue by rgorski** [seamonkeysocial/twitarr#181]
If the server is going to work on UTC, then the time output on the page will need to be updated.

In a remarkable twist, the cruise will be entirely in sync with Eastern Time for the duration. The first day in Eastern Standard Time, and the rest in Eastern Daylight Time, just like Florida land time. It seems likely that any phone that knows it is in Eastern Time when it is put into airplane mode will know to make this change.

**Comment by hendricksond** [comment]
Only the beta server is running in UTC. The server on board will be in Eastern Time.

**Comment by hendricksond** [comment]
Good to know everything will be in Eastern Time this year. We'll definitely be evaluating the schedule export once it's released to see if we need to do any manipulation to account for the switch between EST and EDT.

**Comment by rgorski** [comment]
Yes. The text on that page will still need to be updated to reflect that.

**Comment by hendricksond** [comment]
Ahh, good point. Re-opening!
