### ISSUE TITLE
create user flow does not have an API endpoint

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#2]

**Comment by hendusoone** [comment]
POST api/v2/user/new
Params:
new_username
new_password
email
security_question
security_answer

After creation, user is automatically logged in. Returns the auth key, as well as a user object.

**Comment by hendusoone** [comment]
There is no new_password2 field for api user creation - if user is required to confirm their password by entering it twice, that validation should be done client-side. Server-side, we just check that the username does not exist, and the password is more than 6 characters.
