### ISSUE TITLE
Unable to use iPhone camera - App crashes

### ISSUE THREAD

**Issue by va-peterson** [seamonkeysocial/twitarr#224]
IOS 12.1.4
iPhone SE
When adding a photo, I can access and add from my photo library just fine, but when I try to access the camera, the app closes down and I have to start it up again.
Yes, I saw that @lila had the same issue, but I cannot find her ticket.

**Comment by hendricksond** [comment]
The issue is over in the cruisemonkey repo - https://github.com/seamonkeysocial/cruisemonkey/issues/163
