### ISSUE TITLE
Android: error creating new forum with photo

### ISSUE THREAD

**Issue by geordanr** [seamonkeysocial/twitarr#227]
Got the following error (Photo could not be read: Unsupported marker type 0x04) when creating a new public forum and attaching a photo using the camera icon.

Device is a Pixel 2 running Android 9, running the latest security patch.

![screenshot_20190226-234744](https://user-images.githubusercontent.com/334985/53474169-3d66f480-3a21-11e9-8025-fcd890ba7d26.png)

**Comment by geordanr** [comment]
I'm not sure if I can; it was taken using the camera while in Rainbow Monkey, so the actual photo taken wasn't saved anywhere.

**Comment by hendricksond** [comment]
I'm not sure if the LG G6 behaves differently from the Pixel 2, but when I take a photo in Rainbow Monkey, it saves the photo to my phone's Gallery too. Can you check there? If it's there, please add it to a zip file and attach it here.

**Comment by geordanr** [comment]
Unfortunately, photos taken via other apps don't appear to be saved (tried checking local storage).

**Comment by geordanr** [comment]
I was able to attach a couple pictures via the camera (despite a couple failures immediately prior); I don't know what's different about the successful ones.

**Comment by hendricksond** [comment]
Hey @geordanr , some updates have gone in that should resolve this. I'm going to close the issue, but if you run into it again, please let me know!
