### ISSUE TITLE
Android: error attaching photo from Photos

### ISSUE THREAD

**Issue by geordanr** [seamonkeysocial/twitarr#228]
Got error `Failed: Photo could not be read: Not a JPEG file: starts with 0x89 0x50. Tap to retry.` when attaching a photo selected from Photos app.

Device: Pixel 2
OS: Android 9

(As an aside, it would be nice to be able to attach pictures without having to send a message; current workaround is to make the message be a single space character to enable sending the message.)

![screenshot_20190227-000431](https://user-images.githubusercontent.com/334985/53474911-61c3d080-3a23-11e9-84e8-3ace84049e55.png)

**Comment by geordanr** [comment]
This is the photo I was attempting to attach (at least, this is what Google Photos gave me when I asked to download it):

![lagoon_nebula](https://user-images.githubusercontent.com/334985/53540603-1533d000-3acb-11e9-8ae4-98084724c914.png)

**Comment by hendricksond** [comment]
The photo works for me when I download from here then try to upload it. Could have been some strange interaction between Google Photos and Rainbow Monkey. Was the image saved locally, or in the cloud? It sounds like cloud. I just tried with a few of mine, and they worked, but I think they were actual .jpg files, not .png. I'll do some more testing.

**Comment by hendricksond** [comment]
Very odd. I added the photo to my Google Photos cloud, then attached it to a post in Rainbow Monkey through Google Photos. It worked fine for me. I'm stumped here.

**Comment by geordanr** [comment]
Did a few more tests, and was able to attach photos successfully -- as long as there was a message that had anything other than whitespace.  If the message is entirely whitespace then I get errors.

**Comment by hendricksond** [comment]
Thanks. Fields with only whitespace shouldn't pass validation, anyway. I'll open a separate ticket for that. Closing this one!
