### ISSUE TITLE
New accounts should start off with everything marked as read

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#246]
When someone creates an account, all the forums are marked as "new" because they haven't read any of them yet. It's a bit weird when you create an account and there's lots of existing forums.

**Comment by hendricksond** [comment]
I have created a usability poll about this on the beta server. If users think it's a good idea, it will be implemented server-side.

**Comment by hendricksond** [comment]
Based on the poll, this won't be done.
