### ISSUE TITLE
"Upcoming favorited events" endpoint

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#282]
People have requested a way to get notifications when a favorited event is coming up. I considered just hitting `GET /api/v2/event/mine/:epoch` whenever I ping for seamails, but the problem is that I don't trust the user's device's clock, so I've no idea what epoch to suggest. (Also it wouldn't work great around midnight.)

It would be great if there was an endpoint for "all events that the user has favorited that are scheduled to start in the next 5 minutes" (or something). Then I could hit that whenever I ask for new seamail, and throw up a notification.

See https://github.com/seamonkeysocial/rainbowmonkey/issues/244

**Comment by Hixie** [comment]
actually I just realized I can probably do this by using the end point that gets the server's time.

**Comment by hendricksond** [comment]
`/api/v2/event/mine_soon/{mintues}` has been added.
