### ISSUE TITLE
IDs for seamails, uploads, etc, are sequential

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#288]
I noticed the new server's IDs are sequential, which leaks information (e.g. how many seamail threads people have sent, whether anyone sent one between the last two that you created, etc); is that a concern? I also noticed that it numbers the images sequentially, which will make it easy for people to crawl all of them (I noticed because it turns out Rainbow Monkey caches the images and the same ID got reused for two different images before and after our last data wipe).

cc @hendricksond

**Comment by hendricksond** [comment]
It's only really a concern for photos. It doesn't really matter if people know how many seamails are sent - they won't be able to access them.

It may be a concern for photos - given the sequential IDs there, someone could scrape all photos without actually browsing to them. Sure, all photos are public, but that's not really something we want to encourage. I'll look at changing what we use for ID for photos.
