### ISSUE TITLE
Error message for overlong hashtag has a typo

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#289]
When you submit a new forum with an original message containing a hashtag longer than 100 characters, the server says "Posts is invalid". Should probably be "Post is invalid".

**Comment by hendricksond** [comment]
There's no easy way to de-pluralize "Posts", since Rails is auto-generating that based on a has many relation. Instead, I'm going to suppress that validation, since the custom validator already handles post errors.
