### ISSUE TITLE
/api/v2/event/mine_soon/:minutes should include server time

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#304]
It'd be fantastic if /api/v2/event/mine_soon/:minutes could also include the `epoch` from /api/v2/time. That way I'd be able to accurately tell when the notifications should go away, even if the device clock is way off (which is common on boat).

Thanks!

see also https://github.com/seamonkeysocial/rainbowmonkey/issues/297

**Comment by hendricksond** [comment]
Code is done, just haven't merged it yet. I've added current server time to all event list endpoints, will be returned in the field `now`.

**Comment by Hixie** [comment]
nice

**Comment by hendricksond** [comment]
Fixed by #305
