### ISSUE TITLE
PhotoDetails.id is now an int, not a string

### ISSUE THREAD

**Issue by challfry** [seamonkeysocial/twitarr#326]
As of 4bd5dc05b379d84ba867baaecf53329c1e1be4d2. 

rest_documentation.md describes this field as string-valued, current response format is:

```
            "photo": {
                "animated": false,
                "id": 3,
                "sizes": {
                    "full": "1900x1200",
                    "medium_thumb": "800x505",
                    "small_thumb": "200x200"
                }
```

**Comment by challfry** [comment]
Swift's Codable JSON parser kinda has a reputation as being super finicky.

**Comment by hendricksond** [comment]
I will eventually be changing this back to string - in particular, a UUID.
