### ISSUE TITLE
Emoji being stripped from stream posts

### ISSUE THREAD

**Issue by challfry** [seamonkeysocial/twitarr#327]
A POST to /api/v2/stream with an HTTP body of:

{"text":"Lots of Emoji 😂❤️♻️😍♥️😭"}

produces a StreamPost:

```       
 {
            "author": {
                "display_name": "james",
                "last_photo_updated": 1581054048710,
                "username": "james"
            },
            "id": "34",
            "locked": false,
            "parent_chain": [],
            "reactions": {},
            "text": "Lots of Emoji ",
            "timestamp": 1581058731158
        },
```

That is, the actual emoji have been stripped.

**Comment by challfry** [comment]
Info update: emoji are being stripped from forum posts as well, but not from forum subjects.

**Comment by hendricksond** [comment]
Root cause: https://github.com/twitter/twitter-text/issues/275

**Comment by hendricksond** [comment]
Fixed it with a monkey patch. This will have to do until upstream is fixed.
