### ISSUE TITLE
Question: Is this the app that was available at joco.hollandamerica.com on the 2018 cruise?

### ISSUE THREAD

**Issue by rognstad** [seamonkeysocial/twitarr#5]
I sure thought that was an Angular app. I don't see much of anything on the old Angular branch here. I'd be happy to do some PRs, but I don't have much to offer when it comes to Ruby.

**Comment by grundoon** [comment]
Twitarr is the backend server and webapp and I believe uses Ember, whereas the client is CruiseMonkey and has an Angular history. The cruisemonkey you see in this group, however, is a fresh project – https://github.com/RangerRick/CruiseMonkey is the one that has been used for years on ship.

**Comment by rognstad** [comment]
Thanks!
