### ISSUE TITLE
shiptimezoneoffset API endpoint

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#6]
To be able to reliably show the calendar with the correct times regardless of the accuracy of the device clock or device time zone, it would be nice to have an explicit API end point that specifies the offset from UTC of the ship's local time. Then, calendar events could just be displayed in that time zone.

**Comment by hendricksond** [comment]
I have added an offset to the time endpoint. It will give the server's time offset from UTC.

Time zones have always been difficult on the ship. In the past, I believe the server's clock has been set to match the ship's clock. Hopefully this will be good enough. We can discuss other solutions, but anything we come up with will depend on how we receive the schedule/what time zone(s) are used in the export.

**Comment by hendricksond** [comment]
Ignore previous reference - wrong number 😆
